# Generated by Django 5.2.7 on 2025-10-16 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlinput',
            name='instant_forward',
            field=models.BooleanField(default=False),
        ),
    ]
