# Generated by Django 5.2.7 on 2025-10-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0002_urlinput_instant_forward'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=256)),
            ],
        ),
    ]
