# Generated by Django 5.2.7 on 2025-10-18 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortlink', '0003_domainadd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_custom', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='DomainAdd',
        ),
        migrations.AlterField(
            model_name='urlinput',
            name='url_new',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='urlinput',
            name='url_original',
            field=models.CharField(max_length=512, unique=True),
        ),
        migrations.AddField(
            model_name='urlinput',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shortlink.domain'),
        ),
    ]
