# Generated by Django 5.2.7 on 2025-10-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='show_on_list',
            field=models.BooleanField(default=True),
        ),
    ]
