# Generated by Django 5.2.7 on 2025-10-20 05:34

import misc.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_file', models.CharField(max_length=69, unique=True)),
                ('file_upload', models.FileField(upload_to=misc.models.RandomFileName(''))),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
