# Generated by Django 5.2.7 on 2025-10-20 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_custom', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shortener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_original', models.URLField(max_length=512, unique=True)),
                ('url_new', models.CharField(max_length=25, unique=True)),
                ('instant_forward', models.BooleanField(default=False)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='misc.domain')),
            ],
        ),
    ]
