# Generated by Django 5.2.7 on 2025-10-20 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_domain_shortener'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Domain', 'verbose_name_plural': 'Domains'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': 'File', 'verbose_name_plural': 'Files'},
        ),
        migrations.AlterModelOptions(
            name='shortener',
            options={'verbose_name': 'Short link', 'verbose_name_plural': 'Short links'},
        ),
    ]
