# Generated by Django 5.2.7 on 2025-10-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_alter_domain_options_alter_file_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortener',
            name='disable',
            field=models.BooleanField(default=False),
        ),
    ]
